Repository AssetRipper/AssetRipper, pull requests merged in 2024-02, with the labels that each got.

#1199 Update es.json
  Localizations/es.json
Labels: size/L

#1201 Fixed some properties in BlendTree's ChildMotion
  Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs
Labels: size/S

#1200 FIX: Single script decompilation failure causes half-baked result
  Source/AssetRipper.Export.UnityProjects/Scripts/ScriptDecompiler.cs
Labels: size/S

#1204 Tracker Module Support (.it, .xm, .s3m, .mod)
  Source/AssetRipper.Export.UnityProjects/Audio/AudioClipDecoder.cs
Labels: size/M
