Repository AssetRipper/AssetRipper, pull requests merged in 2024-05, with the labels that each got.

#1335 AnimationClipConverter Fixes
  Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs
  Source/AssetRipper.SourceGenerated.Extensions/StreamedClipExtensions.cs
Labels: size/S

#1336 Fix Incorrect Pass Export Name in Shader Disassembly Mode
  Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
Labels: size/XS

#1337 Fix output error in Disassembly Mode
  Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
Labels: size/S

#1338 Fix color definition in Shader Properties
  Source/AssetRipper.Export.Modules.Shader/IO/SerializedExtensions.cs
Labels: size/XS

#1365 fix alignment and missing script types for writing of `SerializedFile`
  Source/AssetRipper.IO.Files/SerializedFiles/SerializedFile.cs
Labels: size/M
