Repository AssetRipper/AssetRipper, pull requests merged in 2024-06, with the labels that each got.

#1373 Translations update from Weblate
  Localizations/el.json
Labels: size/L

#1374 Consider the aabb in the mesh engine assets key
  Source/AssetRipper.Export.UnityProjects/AssetRipper.Export.UnityProjects.csproj
  Source/AssetRipper.Export.UnityProjects/EngineAssets/EngineAssetsFactory.cs
  Source/AssetRipper.Export.UnityProjects/EngineAssets/PredefinedAssetCache.cs
  Source/AssetRipper.Import/AssetRipper.Import.csproj
Labels: size/S

#1380 Translations update from Weblate
  Localizations/ru.json
Labels: size/M

#1387 Translations update from Weblate
  Localizations/el.json
Labels: size/S

#1397 Update Cpp2IL
  Source/AssetRipper.Decompilation.CSharp/AssetRipper.Decompilation.CSharp.csproj
  Source/AssetRipper.Decompilation.CSharp/CSharpDecompiler.cs
  Source/AssetRipper.Decompilation.CSharp/MethodScopedNameGenerator.cs
  Source/AssetRipper.Decompilation.CSharp/NameGenerator.cs
  Source/AssetRipper.Decompilation.CSharp/TypeScopedNameGenerator.cs
  Source/AssetRipper.Import/AssetRipper.Import.csproj
  Source/AssetRipper.Import/Structure/Assembly/Managers/MonoManager.cs
  Source/AssetRipper.Import/Structure/Assembly/Mono/MonoType.cs
  Source/AssetRipper.Import/Structure/Assembly/PrimitiveType.cs
  Source/AssetRipper.Processing/Assemblies/MethodStubbingProcessor.cs
  Source/AssetRipper.Processing/AssetRipper.Processing.csproj
  Source/AssetRipper.SerializationLogic.Tests/GetFieldsInTypeAndBaseTests.cs
  Source/AssetRipper.SerializationLogic.Tests/Usings.cs
  Source/AssetRipper.SerializationLogic/AssetRipper.SerializationLogic.csproj
  Source/AssetRipper.SerializationLogic/FieldSerializationLogic.cs
  Source/AssetRipper.SerializationLogic/TypeDefinitionConverter.cs
  Source/AssetRipper.SerializationLogic/Usings.cs
Labels: size/M
