Repository AssetRipper/AssetRipper, pull requests merged in 2024-03, with the labels that each got.

#1210 AnimationClip Recovery Improvements
  Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs
  Source/AssetRipper.Processing/AnimationClips/CustomCurveResolver.cs
  Source/AssetRipper.Processing/AnimationClips/Editor/StreamedCurveKey.cs
  Source/AssetRipper.SourceGenerated.Extensions/AnimationClipBindingConstantExtensions.cs
Labels: size/XL

#1244 add nuget.config
  .github/workflows/docfx_build.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  nuget.config
Labels: size/S

#1236 Translations update from Weblate
  Localizations/ru.json
Labels: size/S

#1245 remove the washi source in csproj files
  Source/AssetRipper.Decompilation.CSharp/AssetRipper.Decompilation.CSharp.csproj
Labels: size/XS

#1262 Include datapack.unity3d asset bundle
  Source/AssetRipper.Import/Structure/Platforms/PlatformGameStructure.cs
Labels: size/S

#1249 Redo font previewer
  Source/AssetRipper.GUI.Web/Pages/Assets/FontTab.cs
Labels: size/M

#1275 Fix exported shaders filename bug in Unity 5.5.0+ Resources/AssetBundles
  Source/AssetRipper.Export.UnityProjects/ExportCollection.cs
Labels: size/XS
